Repository consuldemocracy/installer, pull requests merged in 2022-06, with the labels that each got.

#196 Use systemd to start Errbit
  group_vars/all
  roles/errbit/tasks/main.yml
  roles/errbit/templates/errbit.service
Labels: Maintenance, Devops, 1.5

#197 Make SMTP settings example consistent
  README.md
Labels: Bug, Devops, Documentation, 1.5

#195 Clarify sudo and wheel for Ubuntu
  README.md
Labels: Devops, Documentation, 1.5

#199 Fix mini_racer compilation when installing Errbit
  roles/errbit/tasks/main.yml
Labels: Maintenance, Devops, 1.5
